edition: 1.0.0
name: web-framework-app
access: "{{ access }}"

vars:
  region: "{{ region }}"
  memorySize: "{{ memorySize }}"
  service:
    name: "{{ serviceName }}"
    description: '快速部署色情文本检测 项目地址 https://github.com/duolabmeng6/paddlePornDetection'

services:
  framework:
    component: fc
    props:
      region: ${vars.region}
      service:
        name: ${vars.service.name}
        description: ${vars.service.description}
        internetAccess: true
        role:
          name: paddlerole
          policies:
            - AliyunContainerRegistryReadOnlyAccess
      function:
        name: "{{ functionName }}"
        description: ${vars.service.description}
        runtime: custom-container
        memorySize: ${vars.memorySize}
        caPort: 9000
        codeUri: ./
        timeout: 60
        customContainerConfig:
          image: registry-vpc.${vars.region}.aliyuncs.com/duolabmeng/porn_detection_lstm:1.1
          command: '["sh","/app/start.sh"]'
        environmentVariables:
          testEnv: true
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
